### ISSUE TITLE
Large arithmetic expressions overflow

### ISSUE THREAD

**Issue by tarcieri** [jbarnette/johnson#11]
<pre><code>>> Johnson::Parser.parse "1000 * 60 * 60 * 24 * 30"
=> [[:lit, -2147483648]]
</code></pre>

**Comment by jbarnette** [comment]
Argh, good catch. This constant folding may be happening in SpiderMonkey's parser. If it's in the translation bits on our side, what do you think would be the least surprising behavior? Bignum?

**Comment by tarcieri** [comment]
Yes, Bignum would be fine.  We're just round-tripping everything while doing some AST munging, so as long as what goes in comes out I don't really care what the intermediate representation is.

**Comment by jbarnette** [comment]
Okay, Aaron and I are doing a quick round of blameshifting, and then we'll see what we can do about this. In the meantime, a patch (even if it's just a failing testcase) is most welcome. :)

**Comment by jbarnette** [comment]
I, uh, think I'll close this. :heart:
