### ISSUE TITLE
apply(o) causes "arrayLike is undefined" error at prelude.js:35

### ISSUE THREAD

**Issue by Mask** [jbarnette/johnson#15]
simple example:

```
var my = { foo: function() { return true; }}
my.foo.apply(my);
```

I suggest the following change:
    --- a/lib/johnson/js/prelude.js
    +++ b/lib/johnson/js/prelude.js
    @@ -30,7 +30,7 @@ Object.defineProperty(String.prototype, "toSymbol", function() {
     (function(origApply) {
       Object.defineProperty(Function.prototype, "apply", function(thisObj, arrayLike) {
         var realArray = arrayLike;
    -    if (!(arrayLike instanceof Array)) {
    +    if (arrayLike !== undefined && !(arrayLike instanceof Array)) {
           realArray = [];
           for (var i = arrayLike.length - 1; i >= 0; i--) {
             realArray[i] = arrayLike[i];

**Comment by matthewd** [comment]
Fixed in 08405b447d2db8c4abc3864860f9e798400ce653, thanks!

A little experimentation showed that it should also treat null as an empty array... and I noticed there were some other values we'd silently convert that we probably shouldn't.
