### ISSUE TITLE
JS engine warning: leaking GC root 'JSScriptProxy' on Rails Server Shutdown

### ISSUE THREAD

**Issue by shwoodard** [jbarnette/johnson#16]
Title pretty much says it all.  Full message is,

S engine warning: leaking GC root 'JSScriptProxy' at 0x20d3568
JS engine warning: 1 GC root remains after destroying the JSRuntime at 0x3648000.
                   This root may point to freed memory. Objects reachable
                   through it have not been finalized.
script/server:3: [BUG] Bus Error
ruby 1.8.7 (2009-06-12 patchlevel 174) [i686-darwin9.8.0], MBARI 0x8770, Ruby Enterprise Edition 20090928

**Comment by shwoodard** [comment]
The following happened in the middle of execution, not at shutdown.

JS engine warning: leaking GC root 'JSScriptProxy' at 0x2229638
JS engine warning: leaking GC root 'JSScriptProxy' at 0x21ddbb0
JS engine warning: 2 GC roots remain after destroying the JSRuntime at 0x36ea000.
                   These roots may point to freed memory. Objects reachable
                   through them have not been finalized.
/Users/sam.woodard/Development/visa.git/app/models/business.rb:150: [BUG] Bus Error
ruby 1.8.7 (2009-06-12 patchlevel 174) [i686-darwin9.8.0], MBARI 0x8770, Ruby Enterprise Edition 20090928

**Comment by matthewd** [comment]
Could you please try uncommenting the '#define LEAK_ROOT_NAMES' in ext/spidermonkey/runtime.h, to determine which script(s) are leaking?

**Comment by matthewd** [comment]
Actually, a better first question is probably: are you running the last released gem, or newer code from git?

**Comment by shwoodard** [comment]
I built the gem from source after cloning the repo from github.  This worked better.  However, now, I am trying to get another dev env working and I am getting `gem_original_require': no such file to load -- johnson/spidermonkey/spidermonkey (MissingSourceFile) after install Johnson.  Any help?

**Comment by matthewd** [comment]
Sorry, I missed a path change during some rearranging.

887053b9fdbe37b642ac12760bf56eec695eb237 should improve things.
