### ISSUE TITLE
Cannot Install Gem on Solaris

### ISSUE THREAD

**Issue by shwoodard** [jbarnette/johnson#17]
Are there any dependencies that I am forgetting?  Here is the error,

ERROR:  Error installing johnson:
        ERROR: Failed to build gem native extension.

/opt/ruby-enterprise-1.8.7-20090928/bin/ruby extconf.rb
make: Fatal error in reader: config.mk, line 41: Unexpected end of line seen
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/ruby-enterprise-1.8.7-20090928/bin/ruby
extconf.rb:25:in `<<': can't convert nil into String (TypeError)
        from extconf.rb:25

**Comment by jbarnette** [comment]
As far as I know, you're the first person to even **try** compiling Johnson on Solaris, especially with REE. :) The devs are all on Mac OS X or Linux. Line 25, the one with the error, is manipulating an extconf global variable that should certainly exist.

We currently bundle (and statically link) SpiderMonkey with Johnson's native extension, so it's probably not a missing dependency.

I'd try playing with extconf.rb: you can re-run it from the ext/spidermonkey directory (ruby extconf.rb) to regenerate a Makefile.

**Comment by shwoodard** [comment]
If I can successfully install spidermonkey, can I remove the vendor folder of the gem and use the install software on the system?  What would I need to change in the gem?

Thanks,
Sam

**Comment by shwoodard** [comment]
I have successfully built and installed spidermonkey on solaris.  Can I build the johnson gem to point to this rather than the version in vendor/spidermonkey?

**Comment by jbarnette** [comment]
No, Johnson must use its own Spidermonkey (it's patched in a few small ways, and we need to enforce an exact version match). If you can successfully build the copy under vendor, though, I'd be delighted to take any patches to the build/install.
