### ISSUE TITLE
Build error on OS X snowy (/jsatom.h:69: error: size of array ‘arg’ is negative)

### ISSUE THREAD

**Issue by josephwilk** [jbarnette/johnson#22]
I'm having problems building Johnson on OS X snowy machine.

ruby 1.8.7 (2009-06-12 patchlevel 174) [i686-darwin9]

I'm getting an error: 

/Users/josephwilk/Workspace/ruby/johnson/vendor/spidermonkey/jsatom.h:69: error: size of array ‘arg’ is negative

Full console dump included below:

@@@
(in /Users/josephwilk/Workspace/ruby/johnson)
warning: couldn't activate the debugging plugin, skipping
warning: couldn't activate the doofus plugin, skipping
warning: couldn't activate the git plugin, skipping
mkdir -p tmp/i686-darwin9/spidermonkey/1.8.7
cd tmp/i686-darwin9/spidermonkey/1.8.7
/opt/local/bin/ruby -I. ../../../../ext/spidermonkey/extconf.rb
cat: ../../dist/Darwin_DBG.OBJ/nspr/Version: No such file or directory
cd editline; make -f Makefile.ref all
cc -o Darwin_DBG.OBJ/editline.o -c -Wall -Wno-format -MMD -DXP_UNIX -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk  -DJSFILE  -DANSI_ARROWS -DHAVE_TCGETATTR -DHIDE -DUSE_DIRENT -DSYS_UNIX -DHAVE_STDLIB -DUNIQUE_HISTORY editline.c
editline.c: In function ‘readline’:
editline.c:1038: warning: implicit declaration of function ‘getpid’
editline.c: In function ‘add_history’:
editline.c:1051: warning: pointer targets in passing argument 2 of ‘strcmp’ differ in signedness
cc -o Darwin_DBG.OBJ/sysunix.o -c -Wall -Wno-format -MMD -DXP_UNIX -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk  -DJSFILE  -DANSI_ARROWS -DHAVE_TCGETATTR -DHIDE -DUSE_DIRENT -DSYS_UNIX -DHAVE_STDLIB -DUNIQUE_HISTORY sysunix.c
ar rv Darwin_DBG.OBJ/libedit.a Darwin_DBG.OBJ/editline.o Darwin_DBG.OBJ/sysunix.o
ar: creating archive Darwin_DBG.OBJ/libedit.a
a - Darwin_DBG.OBJ/editline.o
a - Darwin_DBG.OBJ/sysunix.o
ranlib Darwin_DBG.OBJ/libedit.a
make -f Makefile.ref  Darwin_DBG.OBJ/libjs.a Darwin_DBG.OBJ/libjs.dylib Darwin_DBG.OBJ/js  Darwin_DBG.OBJ/jsautocfg.h Darwin_DBG.OBJ/jscpucfg Darwin_DBG.OBJ/jscpucfg.o
cat: ../../dist/Darwin_DBG.OBJ/nspr/Version: No such file or directory
make[1]: Circular jscpucfg.h <- Darwin_DBG.OBJ/jsautocfg.h dependency dropped.
cc -o Darwin_DBG.OBJ/jscpucfg.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jscpucfg.c
cc -o Darwin_DBG.OBJ/jscpucfg Darwin_DBG.OBJ/jscpucfg.o
make[1]: Circular Darwin_DBG.OBJ/jsautocfg.h <- Darwin_DBG.OBJ/jsautocfg.h dependency dropped.
rm -f Darwin_DBG.OBJ/jsautocfg.h
Darwin_DBG.OBJ/jscpucfg > Darwin_DBG.OBJ/jsautocfg.h
cc -o Darwin_DBG.OBJ/jsapi.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsapi.c
jsapi.c: In function ‘JS_ConvertArgumentsVA’:
jsapi.c:272: warning: passing argument 5 of ‘TryArgumentFormatter’ from incompatible pointer type
jsapi.c: In function ‘JS_PushArgumentsVA’:
jsapi.c:380: warning: passing argument 5 of ‘TryArgumentFormatter’ from incompatible pointer type
cc -o Darwin_DBG.OBJ/jsarena.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsarena.c
cc -o Darwin_DBG.OBJ/jsarray.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsarray.c
cc -o Darwin_DBG.OBJ/jsatom.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsatom.c
cc -o Darwin_DBG.OBJ/jsbool.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsbool.c
cc -o Darwin_DBG.OBJ/jscntxt.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jscntxt.c
cc -o Darwin_DBG.OBJ/jsdate.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsdate.c
cc -o Darwin_DBG.OBJ/jsdbgapi.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsdbgapi.c
cc -o Darwin_DBG.OBJ/jsdhash.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsdhash.c
cc -o Darwin_DBG.OBJ/jsdtoa.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsdtoa.c
cc -o Darwin_DBG.OBJ/jsemit.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsemit.c
cc -o Darwin_DBG.OBJ/jsexn.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsexn.c
cc -o Darwin_DBG.OBJ/jsfun.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsfun.c
cc -o Darwin_DBG.OBJ/jsgc.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsgc.c
cc -o Darwin_DBG.OBJ/jshash.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jshash.c
cc -o Darwin_DBG.OBJ/jsinterp.o -c -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ   jsinterp.c
cc -o Darwin_DBG.OBJ/jsinvoke.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsinvoke.c
cc -o Darwin_DBG.OBJ/jsiter.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsiter.c
cc -o Darwin_DBG.OBJ/jslock.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jslock.c
cc -o Darwin_DBG.OBJ/jslog2.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jslog2.c
cc -o Darwin_DBG.OBJ/jslong.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jslong.c
cc -o Darwin_DBG.OBJ/jsmath.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsmath.c
cc -o Darwin_DBG.OBJ/jsnum.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsnum.c
cc -o Darwin_DBG.OBJ/jsobj.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsobj.c
cc -o Darwin_DBG.OBJ/jsopcode.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsopcode.c
cc -o Darwin_DBG.OBJ/jsparse.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsparse.c
cc -o Darwin_DBG.OBJ/jsprf.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsprf.c
cc -o Darwin_DBG.OBJ/jsregexp.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsregexp.c
cc -o Darwin_DBG.OBJ/jskwgen.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jskwgen.c
cc -o Darwin_DBG.OBJ/jskwgen -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ   Darwin_DBG.OBJ/jskwgen.o
Darwin_DBG.OBJ/jskwgen Darwin_DBG.OBJ/jsautokw.h
cc -o Darwin_DBG.OBJ/jsscan.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsscan.c
cc -o Darwin_DBG.OBJ/jsscope.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsscope.c
cc -o Darwin_DBG.OBJ/jsscript.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsscript.c
cc -o Darwin_DBG.OBJ/jsstr.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsstr.c
cc -o Darwin_DBG.OBJ/jsutil.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsutil.c
cc -o Darwin_DBG.OBJ/jsxdrapi.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsxdrapi.c
cc -o Darwin_DBG.OBJ/jsxml.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  jsxml.c
cc -o Darwin_DBG.OBJ/prmjtime.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  prmjtime.c
ar rv Darwin_DBG.OBJ/libjs.a Darwin_DBG.OBJ/jsapi.o Darwin_DBG.OBJ/jsarena.o Darwin_DBG.OBJ/jsarray.o Darwin_DBG.OBJ/jsatom.o Darwin_DBG.OBJ/jsbool.o Darwin_DBG.OBJ/jscntxt.o Darwin_DBG.OBJ/jsdate.o Darwin_DBG.OBJ/jsdbgapi.o Darwin_DBG.OBJ/jsdhash.o Darwin_DBG.OBJ/jsdtoa.o Darwin_DBG.OBJ/jsemit.o Darwin_DBG.OBJ/jsexn.o Darwin_DBG.OBJ/jsfun.o Darwin_DBG.OBJ/jsgc.o Darwin_DBG.OBJ/jshash.o Darwin_DBG.OBJ/jsinterp.o Darwin_DBG.OBJ/jsinvoke.o Darwin_DBG.OBJ/jsiter.o Darwin_DBG.OBJ/jslock.o Darwin_DBG.OBJ/jslog2.o Darwin_DBG.OBJ/jslong.o Darwin_DBG.OBJ/jsmath.o Darwin_DBG.OBJ/jsnum.o Darwin_DBG.OBJ/jsobj.o Darwin_DBG.OBJ/jsopcode.o Darwin_DBG.OBJ/jsparse.o Darwin_DBG.OBJ/jsprf.o Darwin_DBG.OBJ/jsregexp.o Darwin_DBG.OBJ/jsscan.o Darwin_DBG.OBJ/jsscope.o Darwin_DBG.OBJ/jsscript.o Darwin_DBG.OBJ/jsstr.o Darwin_DBG.OBJ/jsutil.o Darwin_DBG.OBJ/jsxdrapi.o Darwin_DBG.OBJ/jsxml.o Darwin_DBG.OBJ/prmjtime.o
ar: creating archive Darwin_DBG.OBJ/libjs.a
a - Darwin_DBG.OBJ/jsapi.o
a - Darwin_DBG.OBJ/jsarena.o
a - Darwin_DBG.OBJ/jsarray.o
a - Darwin_DBG.OBJ/jsatom.o
a - Darwin_DBG.OBJ/jsbool.o
a - Darwin_DBG.OBJ/jscntxt.o
a - Darwin_DBG.OBJ/jsdate.o
a - Darwin_DBG.OBJ/jsdbgapi.o
a - Darwin_DBG.OBJ/jsdhash.o
a - Darwin_DBG.OBJ/jsdtoa.o
a - Darwin_DBG.OBJ/jsemit.o
a - Darwin_DBG.OBJ/jsexn.o
a - Darwin_DBG.OBJ/jsfun.o
a - Darwin_DBG.OBJ/jsgc.o
a - Darwin_DBG.OBJ/jshash.o
a - Darwin_DBG.OBJ/jsinterp.o
a - Darwin_DBG.OBJ/jsinvoke.o
a - Darwin_DBG.OBJ/jsiter.o
a - Darwin_DBG.OBJ/jslock.o
a - Darwin_DBG.OBJ/jslog2.o
a - Darwin_DBG.OBJ/jslong.o
a - Darwin_DBG.OBJ/jsmath.o
a - Darwin_DBG.OBJ/jsnum.o
a - Darwin_DBG.OBJ/jsobj.o
a - Darwin_DBG.OBJ/jsopcode.o
a - Darwin_DBG.OBJ/jsparse.o
a - Darwin_DBG.OBJ/jsprf.o
a - Darwin_DBG.OBJ/jsregexp.o
a - Darwin_DBG.OBJ/jsscan.o
a - Darwin_DBG.OBJ/jsscope.o
a - Darwin_DBG.OBJ/jsscript.o
a - Darwin_DBG.OBJ/jsstr.o
a - Darwin_DBG.OBJ/jsutil.o
a - Darwin_DBG.OBJ/jsxdrapi.o
a - Darwin_DBG.OBJ/jsxml.o
a - Darwin_DBG.OBJ/prmjtime.o
ranlib: file: Darwin_DBG.OBJ/libjs.a(jslock.o) has no symbols
ranlib: file: Darwin_DBG.OBJ/libjs.a(jslong.o) has no symbols
ranlib Darwin_DBG.OBJ/libjs.a
ranlib: file: Darwin_DBG.OBJ/libjs.a(jslock.o) has no symbols
ranlib: file: Darwin_DBG.OBJ/libjs.a(jslong.o) has no symbols
cc -dynamiclib  -framework System -o Darwin_DBG.OBJ/libjs.dylib Darwin_DBG.OBJ/jsapi.o Darwin_DBG.OBJ/jsarena.o Darwin_DBG.OBJ/jsarray.o Darwin_DBG.OBJ/jsatom.o Darwin_DBG.OBJ/jsbool.o Darwin_DBG.OBJ/jscntxt.o Darwin_DBG.OBJ/jsdate.o Darwin_DBG.OBJ/jsdbgapi.o Darwin_DBG.OBJ/jsdhash.o Darwin_DBG.OBJ/jsdtoa.o Darwin_DBG.OBJ/jsemit.o Darwin_DBG.OBJ/jsexn.o Darwin_DBG.OBJ/jsfun.o Darwin_DBG.OBJ/jsgc.o Darwin_DBG.OBJ/jshash.o Darwin_DBG.OBJ/jsinterp.o Darwin_DBG.OBJ/jsinvoke.o Darwin_DBG.OBJ/jsiter.o Darwin_DBG.OBJ/jslock.o Darwin_DBG.OBJ/jslog2.o Darwin_DBG.OBJ/jslong.o Darwin_DBG.OBJ/jsmath.o Darwin_DBG.OBJ/jsnum.o Darwin_DBG.OBJ/jsobj.o Darwin_DBG.OBJ/jsopcode.o Darwin_DBG.OBJ/jsparse.o Darwin_DBG.OBJ/jsprf.o Darwin_DBG.OBJ/jsregexp.o Darwin_DBG.OBJ/jsscan.o Darwin_DBG.OBJ/jsscope.o Darwin_DBG.OBJ/jsscript.o Darwin_DBG.OBJ/jsstr.o Darwin_DBG.OBJ/jsutil.o Darwin_DBG.OBJ/jsxdrapi.o Darwin_DBG.OBJ/jsxml.o Darwin_DBG.OBJ/prmjtime.o  
cc -o Darwin_DBG.OBJ/js.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  js.c
cc -o Darwin_DBG.OBJ/js -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_josephwilk -DEDITLINE -IDarwin_DBG.OBJ  Darwin_DBG.OBJ/js.o Darwin_DBG.OBJ/libjs.a   \
        editline/Darwin_DBG.OBJ/libedit.a
make[1]: `Darwin_DBG.OBJ/jsautocfg.h' is up to date.
make[1]:`Darwin_DBG.OBJ/jscpucfg' is up to date.
make[1]: `Darwin_DBG.OBJ/jscpucfg.o' is up to date.
checking for jsautocfg.h in /Users/josephwilk/Workspace/ruby/johnson/vendor/spidermonkey/Darwin_DBG.OBJ... yes
checking for jsapi.h in /Users/josephwilk/Workspace/ruby/johnson/vendor/spidermonkey... yes
creating Makefile
cd -
cd tmp/i686-darwin9/spidermonkey/1.8.7
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin10.0
make
/usr/bin/gcc-4.0 -I. -I/opt/local/lib/ruby/1.8/i686-darwin9 -I/opt/local/lib/ruby/1.8/i686-darwin9 -I../../../../ext/spidermonkey -I/Users/josephwilk/Workspace/ruby/johnson/vendor/spidermonkey/Darwin_DBG.OBJ -I/Users/josephwilk/Workspace/ruby/johnson/vendor/spidermonkey -I/opt/local/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE   -fno-common -O2  -fno-common -pipe -fno-common  -g  -Wall  -Wextra  -Wcast-qual  -Wwrite-strings  -Wconversion  -Wmissing-noreturn  -Winline  -DXP_UNIX  -c ../../../../ext/spidermonkey/context.c
/usr/bin/gcc-4.0 -I. -I/opt/local/lib/ruby/1.8/i686-darwin9 -I/opt/local/lib/ruby/1.8/i686-darwin9 -I../../../../ext/spidermonkey -I/Users/josephwilk/Workspace/ruby/johnson/vendor/spidermonkey/Darwin_DBG.OBJ -I/Users/josephwilk/Workspace/ruby/johnson/vendor/spidermonkey -I/opt/local/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE   -fno-common -O2  -fno-common -pipe -fno-common  -g  -Wall  -Wextra  -Wcast-qual  -Wwrite-strings  -Wconversion  -Wmissing-noreturn  -Winline  -DXP_UNIX  -c ../../../../ext/spidermonkey/conversions.c
../../../../ext/spidermonkey/conversions.c: In function ‘convert_symbol_to_js’:
../../../../ext/spidermonkey/conversions.c:34: warning: initialization makes integer from pointer without a cast
../../../../ext/spidermonkey/conversions.c: In function ‘convert_regexp_to_js’:
../../../../ext/spidermonkey/conversions.c:55: warning: initialization makes integer from pointer without a cast
../../../../ext/spidermonkey/conversions.c: In function ‘convert_to_js’:
../../../../ext/spidermonkey/conversions.c:116: warning: initialization makes integer from pointer without a cast
../../../../ext/spidermonkey/conversions.c: In function ‘convert_js_string_to_ruby’:
../../../../ext/spidermonkey/conversions.c:192: warning: passing argument 2 of ‘rb_str_new’ as signed due to prototype
/usr/bin/gcc-4.0 -I. -I/opt/local/lib/ruby/1.8/i686-darwin9 -I/opt/local/lib/ruby/1.8/i686-darwin9 -I../../../../ext/spidermonkey -I/Users/josephwilk/Workspace/ruby/johnson/vendor/spidermonkey/Darwin_DBG.OBJ -I/Users/josephwilk/Workspace/ruby/johnson/vendor/spidermonkey -I/opt/local/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE   -fno-common -O2  -fno-common -pipe -fno-common  -g  -Wall  -Wextra  -Wcast-qual  -Wwrite-strings  -Wconversion  -Wmissing-noreturn  -Winline  -DXP_UNIX  -c ../../../../ext/spidermonkey/debugger.c
In file included from ../../../../ext/spidermonkey/immutable_node.h:6,
                 from ../../../../ext/spidermonkey/debugger.c:4:
/Users/josephwilk/Workspace/ruby/johnson/vendor/spidermonkey/jsatom.h:69: error: size of array ‘arg’ is negative
In file included from /Users/josephwilk/Workspace/ruby/johnson/vendor/spidermonkey/jsgc.h:48,
                 from /Users/josephwilk/Workspace/ruby/johnson/vendor/spidermonkey/jscntxt.h:52,
                 from ../../../../ext/spidermonkey/immutable_node.h:10,
                 from ../../../../ext/spidermonkey/debugger.c:4:
/Users/josephwilk/Workspace/ruby/johnson/vendor/spidermonkey/jsbit.h:220: error: size of array ‘arg’ is negative
make: **\* [debugger.o] Error 1
rake aborted!
Command failed with status (2): [make...]
@@@

**Comment by jbarnette** [comment]
You're missing the tracemonkey git submodule, which isn't documented at the moment. I've pushed a fix to the 'unstable' branch for this, and we'll improve it some more before 2.0.0 proper.
