### ISSUE TITLE
Can't call Ruby predicate methods within Javascript

### ISSUE THREAD

**Issue by mcmire** [jbarnette/johnson#27]
Obviously, Javascript doesn't let you call methods with a question mark on the end like Ruby does. For instance, you can't say `Ruby.File.directory?("/var")`. Now there is a workaround, which is `Ruby.File.send("directory?", "/var")`. However it might be nice to autoconvert method names so I can say `Ruby.File.isDirectory("/var")`. Or perhaps `Ruby.File.directory_("/var")` (or something) to minimize stepping on a predefined `is*` method. WDYT?

**Comment by matthewd** [comment]
`Ruby.File["directory?"]("var")` isn't so bad

**Comment by mcmire** [comment]
Okay, cool. I'm fine with that. So does Johnson convert Ruby methods into Javascript properties whose values are functions? I guess maybe part of the issue is that these kinds of things aren't really documented anywhere.
