### ISSUE TITLE
Don't work with bundler: Needs gemspec

### ISSUE THREAD

**Issue by grimen** [jbarnette/johnson#29]
Tried to use "johnson" with Bundler for Ruby 1.9:

<pre>
gem 'johnson', :git => 'git://github.com/jbarnette/johnson.git', :branch => '1.9.1'
</pre>

...but noticed there's not @johnson.gemspec@ in the repo root. Therefore:

<pre>
Could not find gem 'johnson (>= 0, runtime)' in git://github.com/jbarnette/johnson.git (at 1.9.1).
Source does not contain any versions of 'johnson (>= 0, runtime)'
</pre>

**Comment by grimen** [comment]
I could fix this, but...it's so easy task so I leave it to the author. ;)

**Comment by tenderlove** [comment]
The gemspec will not be checked in.  When the gem is built for release, certain files are generated.  These generated files will not be listed in the gemspec until "rake package" is run.  Try it out, and you'll see the problem.  :-)

**Comment by grimen** [comment]
OK, so is there a good practice for using with Bundler - install manually? :)

**Comment by tenderlove** [comment]
The best practice with bundler is to use the released gem.  ;-)

We're not quite ready for 1.9 support yet.  I'll bug the other folks on the team, and maybe we can get a beta release with 1.9 support.  Then you don't need to install from git.

**Comment by grimen** [comment]
OK, I see. Thanks!
