### ISSUE TITLE
checked in gemspec

### ISSUE THREAD

**Issue by jacquescrocker** [jbarnette/johnson#31]
Please check in a gemspec so we can use johnson with bundler :git. Thanks

**Comment by jbarnette** [comment]
Nope, we don't do that: Checking in a gemspec is a promise to keep it up-to-date constantly. We're happy to do more frequent prereleases or patch releases if people ask for them, though.

**Comment by jacquescrocker** [comment]
Ok. The use case for this was my app was blowing up with johnson (crazy C error) and I wanted to check it with the unstable branch before logging a bug on it.

```
gem "johnson", :git => "http://github.com/jbarnette/johnson.git", :branch => "unstable"
```

**Comment by flavorjones** [comment]
If you want to check with the unstable branch, then just check out the repository and use bundler's :path option:

  gem "johnson", :path => "/my/local/clone/of/johnson"
