### ISSUE TITLE
Johnson cannot handle decimal numbers

### ISSUE THREAD

**Issue by panzi** [jbarnette/johnson#39]
Johnson converts all decimal numbers into integers by cutting of the decimal places:

> > Johnson::Parser.parse("0.5").value[0].value
> > => 0

**Comment by najamkhn** [comment]
Don't use `.parse` use 
 `Johnson::Parser::parse("0.5").value[0].value`

**Comment by panzi** [comment]
Thanks. Indeed, now it works correctly. Why is there this difference? In a ruby chat someone told me once you should use `::` only for constants and not for methods, so I used `.parse`. What is the `::parse` method good for, when it returns such erroneous results?

Anyway, I'm glad I can use the official gem now and do not need to maintain my own.
