### ISSUE TITLE
c.removeAttribute is not a function error

### ISSUE THREAD

**Issue by mattdelacdev** [jbarnette/johnson#44]
When using jQuery version 1.6+, I'm getting that Johnson::Error when running my tests. Any idea how I can fix that without modifying the jQuery source itself?

**Comment by smparkes** [comment]
Third time's a charm: this is actually missing functionality in envjs: removeAttribute is a DOM API.

That said, the Johnson version of envjs is mothballed. I'd suggest trying something based on v8 and/or a headless webkit.
